### ISSUE TITLE
Safe Alarm template entity - An alarm control panel that allows disarming without entering a code.

### ISSUE THREAD

**Issue by allenporter** [allenporter/home-assistant-config#20]
Perhaps there is a way to make this template entity use a blueprint:
```
  - platform: template
    panels:
      safe_alarm:
        unique_id: XXX
        name: Safe Alarm
        code_arm_required: false
        code_format: no_code
        value_template: "{{ states('alarm_control_panel.home_alarm') }}"
        arm_away:
          service: alarm_control_panel.alarm_arm_away
          target:
            entity_id: alarm_control_panel.home_alarm
        arm_home:
          service: alarm_control_panel.alarm_arm_home
          target:
            entity_id: alarm_control_panel.home_alarm
        disarm:
          - service: alarm_control_panel.alarm_disarm
            target:
              entity_id: alarm_control_panel.home_alarm
            data:
              code: !secret alarm_code
```
