### ISSUE TITLE
Inverted cover blueprint template entity

### ISSUE THREAD

**Issue by allenporter** [allenporter/home-assistant-config#21]
This should really be a blueprint template entity, right?

```
  - platform: template
    covers:
      nook_blinds:
        unique_id: YYYY
        device_class: blind
        friendly_name: "Nook Blinds"
        value_template: "{{ state_attr('cover.nook', 'current_position')|float < 100 }}"
        position_template: "{{ 100 - state_attr('cover.nook', 'current_position') | int(100) }}"
        open_cover:
          service: cover.close_cover
          data: {}
          target:
            entity_id: cover.nook
        close_cover:
          service: cover.open_cover
          data: {}
          target:
            entity_id: cover.nook
        stop_cover:
          service: cover.stop_cover
          data: {}
          target:
            entity_id: cover.nook
        set_cover_position:
          service: cover.set_cover_position
          data:
            position: "{{100-position}}"
```
