### ISSUE TITLE
Nest event blueprint template entity

### ISSUE THREAD

**Issue by allenporter** [allenporter/home-assistant-config#22]
Support a blueprint template entity for various event types like this:

```yaml
- trigger:
    platform: device
    device_id: e8f843c4a70e51a8ce27e663ee16827d
    domain: nest
    type: camera_person
  binary_sensor:
    - name: Front Yard Person
      auto_off: 5
      state: "true"
      unique_id: 7e6f2bc0-f10c-11ec-b192-066a07ffbaf5
  unique_id: "3474306b-f10c-11ec-8280-066a07ffbaf5"

- trigger:
    platform: device
    device_id: 8e953284a2a7ca265b98eb54476780ef
    domain: nest
    type: doorbell_chime
  binary_sensor:
    - name: Doorbell Chime
      auto_off: 5
      state: "true"
      unique_id: 7e6f2ba1-f10c-11ec-9de0-066a07ffbaf5
  unique_id: "2eeabec4-f10c-11ec-81e9-066a07ffbaf5"
```
